# Generated by Django 4.1.2 on 2022-11-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canteen",
            fields=[
                ("canteenID", models.AutoField(primary_key=True, serialize=False)),
                ("canteenName", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True, null=True)),
                ("descript", models.TextField(blank=True, null=True)),
                (
                    "logoURL",
                    models.FileField(
                        blank=True, null=True, upload_to="static/canteen/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.DecimalField(decimal_places=0, max_digits=6)),
                (
                    "nickName",
                    models.CharField(
                        default=models.AutoField(primary_key=True, serialize=False),
                        max_length=10,
                    ),
                ),
                ("descript", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dishName", models.CharField(max_length=15)),
                ("dishPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "picURL",
                    models.FileField(blank=True, null=True, upload_to="static/dish/"),
                ),
                (
                    "canteenID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="software.canteen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalPrice", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "canteenID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="software.canteen",
                    ),
                ),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="software.customerinfo",
                    ),
                ),
                ("dishList", models.ManyToManyField(to="software.dish")),
            ],
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("totalPrice__gte", 0), ("totalPrice__lte", 50000)),
                name="Order_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="dish",
            constraint=models.CheckConstraint(
                check=models.Q(("dishPrice__gte", 0), ("dishPrice__lte", 5000)),
                name="dishPrice_number",
            ),
        ),
    ]
